name: checkin

on:
  - push
  - pull_request

jobs:
  checkin:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-checkin
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: install
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 23
          pnpm-version: 9
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: release
        run: pnpm release
      - name: 'check for uncommitted changes'
        # Ensure no changes
        run: |
          pnpm --version
          node --version
          git add .
          if ! git diff --cached --color=always --exit-code -- . ':!node_modules'; then
            echo "::error::Found changed files after build. Please run 'pnpm release' and check in all changes."
            exit 1
          fi
